#!/bin/bash
#
MYSQL=$(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installed")
if [ $MYSQL -eq 0 ]; then
        echo "Paigaldame mysql-server"
        apt-get install -y mysql-server;
elif [ $MYSQL -eq 1 ]; then
        echo "mysql on paigaldatud"
        service mysql-server status
fi

