#!/bin/bash
#
WORDPRESS=$(dpkg-query -W -f='${Status}' wordpress 2>/dev/null | grep -c "ok installed")
if [ $WORDPRESS -eq 0 ]; then
        echo "Paigaldame wordpressi"
        apt-get install -y wordpress;
elif [ $WORDPRESS -eq 1 ]; then
        echo "wordpress on paigaldatud"
        service wordpress status
fi

