#!/bin/bash
kasutajanimi=81 # ./lisa_db kasutajanimi
parool=$(pwgen 6)
dbnimi=$kasutajanimi
# Kontroll
echo $kasutajanimi
echo $parool
echo $dbnimi
kaskl="CREATE DATABASE IF NOT EXISTS $dbnimi;"
kask2="GRANT USAGE ON *.* TO $kasutajanimi@localhost IDENTIFIED BY '$parool';"
kask3="GRANT ALL PRIVILEGES ON $dbnimi.* TO $kasutajanimi@localhost;"
kask4="FLUSH PRIVILEGES;"
sql="${kaskl}$(kask2}${kask3}S{kask4}"
echo $sql
sudo mysql -e "$sql" 2>> /var/log/db_lisa.error.log
if [ $? -eq 0 ]; then
touch /home/Skasutajanimi/.my.cnf
echo "[client]" > /home/$kasutajanimi/.my.cnf
echo "user=$kasutajanimi" >> /home/$kasutajanimi/.my.cnf
echo "password=$parool" >> /home/$kasutajanimi/.my.cnf
echo Skasutajanimi:$kasutajanimi /home/Skasutajanimi/.my.cnf
chmod 400 /home/$kasutajanimi/.my.cnf
fi
