#!/bin/bash
#
PHPMYADMIN=$(dpkg-query -W -f='${Status}' phpmyadmin 2>/dev/null | grep -c "ok installed")
if [ $PHPMYADMIN -eq 0 ]; then
        echo "Paigaldame phpmyadmin"
        apt-get install -y phpmyadmin;
elif [ $PHPMYADMIN -eq 1 ]; then
        echo "phpmyadmin on paigaldatud"
        service phpmyadmin status
fi

